repos:
-   repo: local
    hooks:
    - id: isort
      name: isort
      entry: poetry run isort
      language: system
      types: [python]
      stages: [commit]
      exclude: frux_app_server/migrations|docs
    - id: black
      name: black
      entry: poetry run black
      language: system
      types: [python]
      stages: [commit]
      args: [--skip-string-normalization]
      exclude: frux_app_server/migrations|docs
    - id: flake8
      name: flake8
      entry: poetry run flake8
      language: system
      types: [python]
      stages: [commit]
      args: [--max-line-length=88]
      exclude: frux_app_server/migrations|docs
    - id: mypy
      name: mypy
      entry: poetry run mypy
      language: system
      types: [python]
      stages: [commit]
      exclude: frux_app_server/migrations|docs
    - id: pylint
      name: pylint
      entry: poetry run pylint
      language: system
      types: [python]
      stages: [commit]
      args: [--load-plugins, pylint_flask_sqlalchemy, --disable=E0402]
      exclude: frux_app_server/migrations|docs
